import fs from 'node:fs/promises';
import path from 'node:path';
import { adapters } from '../adapters/index.js';
import { consolidateExisting, type ConsolidateConflict, type ConsolidatedArtifact } from './adopt.js';
import { pathExists } from './fs-utils.js';
import { templatesDir } from './package-root.js';

export interface GenerateFromProjectOptions {
  /** Topic slug used in the unique output dir name. Defaults to `template`. */
  topic?: string;
  /** Explicit output dir. When set, overrides the auto unique dir. */
  dir?: string;
  /** Scaffold locale for the author command files. Defaults to `en`. */
  locale?: string;
  /** Clock injection for deterministic tests. */
  now?: Date;
}

export interface GenerateFromProjectResult {
  genDir: string;
  projectName: string;
  artifacts: ConsolidatedArtifact[];
  conflicts: ConsolidateConflict[];
  excluded: { path: string; reasonKey: string }[];
  writtenPaths: string[];
  toolIds: string[];
}

const PROJECT_NAME = 'harvested';

function timestamp(now: Date): string {
  return now.toISOString().replace(/[:.]/g, '-').replace('T', '_').replace('Z', '');
}

function slugifyTopic(topic: string): string {
  const slug = topic
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || 'template';
}

/**
 * Deterministic part of `imwel template init --from-project`: harvest USER-owned
 * tool artifacts, and generate a structurally valid template-repo skeleton into a
 * unique dir. Semantic organization (splitting projects, roles, README) is left to
 * the `/imwel-create-template` skill. Read-only over the scanned project.
 */
export async function generateTemplateFromProject(
  projectDir: string,
  options: GenerateFromProjectOptions = {},
): Promise<GenerateFromProjectResult> {
  const now = options.now ?? new Date();
  const consolidated = await consolidateExisting(projectDir, adapters, { onlyUser: true });

  const topic = slugifyTopic(options.topic ?? 'template');
  const genDir =
    options.dir ??
    path.join(projectDir, '.imwel', 'generated-templates', `${topic}-${timestamp(now)}`);

  const writtenPaths: string[] = [];
  const projectDirAbs = path.join(genDir, PROJECT_NAME);

  await fs.mkdir(genDir, { recursive: true });
  const manifestPath = path.join(genDir, '.imwel', 'manifest.yaml');
  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, manifestContent(), 'utf8');
  writtenPaths.push(manifestPath);

  const agentsChunks: string[] = [];
  for (const artifact of consolidated.artifacts) {
    if (artifact.type === 'agents') {
      agentsChunks.push(artifact.canonicalContent.trimEnd());
      continue;
    }
    const rel =
      artifact.type === 'skill'
        ? path.join('skills', artifact.slug, 'SKILL.md')
        : path.join('rules', `${artifact.slug}.md`);
    const abs = path.join(projectDirAbs, rel);
    await fs.mkdir(path.dirname(abs), { recursive: true });
    await fs.writeFile(abs, ensureTrailingNewline(artifact.canonicalContent), 'utf8');
    writtenPaths.push(abs);
  }
  if (agentsChunks.length) {
    const abs = path.join(projectDirAbs, 'agents.md');
    await fs.mkdir(path.dirname(abs), { recursive: true });
    await fs.writeFile(abs, ensureTrailingNewline(agentsChunks.join('\n\n')), 'utf8');
    writtenPaths.push(abs);
  }

  writtenPaths.push(...(await copyAuthorCommands(genDir, options.locale ?? 'en')));

  return {
    genDir,
    projectName: PROJECT_NAME,
    artifacts: consolidated.artifacts,
    conflicts: consolidated.conflicts,
    excluded: consolidated.excluded,
    writtenPaths,
    toolIds: consolidated.toolIds,
  };
}

function ensureTrailingNewline(content: string): string {
  return content.endsWith('\n') ? content : `${content}\n`;
}

function manifestContent(): string {
  return [
    '# imwel manifest — generated by `imwel template init --from-project`.',
    '# Refine projects/roles with the /imwel-create-template skill, then `imwel lint`.',
    '',
    'conventions:',
    '  rulesDir: rules',
    '  skillsDir: skills',
    '  agentsFile: agents.md',
    '',
    'projects:',
    `  - name: ${PROJECT_NAME}`,
    `    path: ${PROJECT_NAME}`,
    '    role: project',
    '',
  ].join('\n');
}

/**
 * Copy the family-A author scaffold commands (`/imwel-author`, `/imwel-lint`) into
 * the generated template dir, so its author gets them in place — instead of
 * bundling author commands into the consumer command pack.
 */
async function copyAuthorCommands(genDir: string, locale: string): Promise<string[]> {
  const written: string[] = [];
  const localeCommands = path.join(templatesDir(), 'init', locale, '.cursor', 'commands');
  const fallbackCommands = path.join(templatesDir(), 'init', 'en', '.cursor', 'commands');
  const sourceDir = (await pathExists(localeCommands)) ? localeCommands : fallbackCommands;
  if (!(await pathExists(sourceDir))) {
    return written;
  }
  const destDir = path.join(genDir, '.cursor', 'commands');
  await fs.mkdir(destDir, { recursive: true });
  for (const entry of await fs.readdir(sourceDir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) {
      continue;
    }
    const dest = path.join(destDir, entry.name);
    await fs.copyFile(path.join(sourceDir, entry.name), dest);
    written.push(dest);
  }
  return written;
}
